version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "MCrackLP1"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "*eslint*"
          - "*prettier*"
        dependency-type: "production"
      development-dependencies:
        patterns:
          - "@types/*"
          - "*eslint*"
          - "*prettier*"
          - "typescript"
          - "tsx"
          - "playwright"
        dependency-type: "development"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(ci):"
